apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-backend
  namespace: backend
data:
  DATABASE_PATH: /app/data/missions.db
  N8N_WEBHOOK_URL: http://service-n8n.n8n.svc.cluster.local:5678/webhook/mission-launched