apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
data:
  BACKEND_EVENTS_URL: "http://backend-service.backend.svc.cluster.local:3001/events"
  EXECUTIONS_DATA_SAVE_ON_SUCCESS: "all"
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "false"
  N8N_BLOCK_ENV_ACCESS_IN_NODE: "false"
  N8N_HOST: "0.0.0.0"
  N8N_PORT: "5678"
  N8N_PROTOCOL: "http"
  N8N_SECURE_COOKIE: "false"
  NODE_OPTIONS: "--max-old-space-size=768"
  WEBHOOK_URL: "http://n8n.space-missions.test/"